[package]
name = "yapl"
version = "0.1.0"
authors = ["DavidPRolfe <david.p.rolfe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "yapl"

[dependencies]
thiserror = "1.0.23"
utf8-decode = "1.0.0"